import Head from 'next/head'
import Image from 'next/image'
import Groups from '../components/Groups'
import InfoPage from '../components/InfoPage'
import Intro from '../components/Intro'
import Navbar from '../components/Navbar'
import Podcast from '../components/Podcast'



export default function Home() {
  
  return (
    <div  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Intro/>
        </div>
      
      <InfoPage/>
      <Podcast/>
      <Groups/>
      
    </div>
  )
}
