import Head from 'next/head'
import Image from 'next/image'
import FriendsCards from '../components/FriendsCards'
import Groups from '../components/Groups'
import Groups2 from '../components/Groups2'
import InfoPage from '../components/InfoPage'
import Intro from '../components/Intro'
import Navbar from '../components/Navbar'
import Newcommer from '../components/Newcommer'

import Podcast from '../components/Podcast'





export default function Home() {
  
  return (
    <div  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className="space-y-20 ">
        
        <Intro/>
        
        
        <Groups/>
        <Groups2/>
      <InfoPage/>
      
      <Podcast/>
      <FriendsCards/>
      <Newcommer/>
      
      </div>
      
      
    </div>
  )
}
